import PageLayout from '../../components/layout/PageLayout';

export default function Disclaimer() {
    return (
        <PageLayout 
            title="Disclaimer" 
            subtitle="Understand the limitations of our digital handwriting simulation."
        >
            <h3>General Disclaimer</h3>
            <p>
                The information provided by Handwritten ("we," "us", or "our") on our website is for general informational purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability or completeness of any information on the Site.
            </p>

            <h3>Not Legal Advice</h3>
            <p>
                The digital handwriting generated by this tool is a simulation. It is not a legal substitute for a wet-ink signature in all jurisdictions. We do not provide legal advice regarding the validity of digital signatures or generated handwriting for legal documents (wills, contracts, etc.). Users should consult with legal counsel regarding the acceptance of digitally generated handwriting in formal proceedings.
            </p>

            <h3>Educational Use</h3>
            <p>
                This tool is intended for creative, educational, and productivity purposes. We do not condone the use of this tool for forging documents, academic dishonesty, or fraud. Users are solely responsible for the content they generate and how they use it.
            </p>
            <p className="text-sm text-neutral-400 mt-8">
                Last updated: January 29, 2026
            </p>
        </PageLayout>
    );
}
